name: 'PR Test'

on:
  pull_request:
    types:
      - ready_for_review
    branches-ignore:
      - "release/*"
      - "main"

jobs:
  my-first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello World"